name: CI (example)

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:
  ubuntu-ci:
    name: Spectral ubuntu CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral CI
        uses: spectralops/spectral-github-action@v4
        with:
          spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
          spectral-args: scan --engines iac,secrets